### ISSUE TITLE
install.sh error: cabal does not support --allow-boot-library-installs

### ISSUE THREAD

**Issue by beickhoff** [google/codeworld#560] opened 2017-10-02 01:56 UTC
I'm trying to build codeworld.  I'm running Ubuntu 16.04.1 LTS, and per the caveats I created a new user just for codeworld.  Running install.sh gets as far as this top-level command

<code>RUNNING: ghcjs-boot --dev --ghcjs-boot-dev-branch ghc-8.0 --shims-dev-branch ghc-8.0 --no-prof --no-haddock
</code>

and fails shortly thereafter with the following:

<code>fatal: cabal-install program /home/codeworld/Development/open/codeworld/build/bin/cabal does not support --allow-boot-library-installs (requires version 2.0.0.0 or newer)
</code>

The reference to version 2.0.0.0 or newer seems odd because the version of cabal comes from install.sh itself:

<code>RUNNING: wget https:\//www.haskell.org/cabal/release/cabal-install-1.24.0.2/cabal-install-1.24.0.2.tar.gz
</code>

**Comment by cdsmith** [comment] 2017-10-02 02:31
The problem is https://github.com/ghcjs/ghcjs/commit/3c10d16c8e5333a4e0926486db668c2176caad02, which was committed to the ghc-8.0 branch of GHCJS 10 days ago.  Can you try changing the version of cabal-install to 2.0, and see if that works?  If so, I'll update the install script.

**Comment by beickhoff** [comment] 2017-10-02 09:07
Updating to cabal-install-2.0.0.0 gets me through install.sh, but I run into a different error in build.sh:

<code>RUNNING: cabal_install ./codeworld-server ./codeworld-error-sanitizer ./codeworld-compiler ./codeworld-game-api ./codeworld-prediction ./codeworld-api ./codeworld-game-server
</code>

eventually fails with

```
semigroupoids-5.1-DwSFJnpsikw4rFFDoz3V4Q failed during the configure step. The
exception was:
dieVerbatim: user error (cabal:
'/home/codeworld/Development/open/codeworld/build/bin/ghc' exited with
an error:

/tmp/cabal-tmp-27828/semigroupoids-5.1/dist/setup/setup.hs:8:31: error:
Module
‘Distribution.Package’
does not export
‘PackageName(PackageName)’
)
```

Of course, having never gotten this far, I can't say whether or not this new error is related to the cabal upgrade.

**Comment by cdsmith** [comment] 2017-10-02 14:14
Yes, that's Cabal again.  The easiest thing for you to do is probably use an older GHCJS.  After line 169 (`git clone`) of install.sh, try adding `git reset --hard f743ca7bfee006412376f42c247af1e0a98de95a`.

I'll look into fixing the install process to work with newer Cabal and cabal-install versions.  Sorry for the trouble.

**Comment by beickhoff** [comment] 2017-10-02 14:28
Chris, no trouble at all.  Thank _you_ for taking a look into this, and let me know if you want me to test out something else.  I'll give that hard reset a shot later today as my stopgap solution.

**Comment by jma11** [comment] 2017-10-26 23:34
Chris, we are facing the same problem. We got the same error message when we run build.sh, the "semigroupoids-5. ..." one. Then we added "git reset --hard b82d50fb269ab170e0b9ebedaa82ac532ae2d871" to install.sh, but it fails to finish install.sh. Do you have any suggestions? Or can we use an older version of GHCJS that does not have this problem?

**Comment by cdsmith** [comment] 2017-11-01 01:52
I'm not sure why fixing the GHCJS version didn't work.  It did for me.

In any case, the underlying problem should be fixed now, so it's no longer necessary.  Sorry for the trouble.

**Closed** 2017-11-01 01:51 UTC
Labels: bug
