### ISSUE TITLE
User-reported unhelpful error message

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1151] opened 2019-09-10 12:59 UTC
**Program:** https://code.world/#PXxYFrNmVilr525wlMiC8Qw

**Comment:**

There is nothing on the line that the screen is telling me I have an error on.

**Message:**

    program.hs:8:1: error:
        parse error (possibly incorrect indentation or mismatched brackets)

**Comment by cdsmith** [comment] 2019-09-10 13:13
In a shallow sense, this is a duplicate of #597.

I wonder if there's a way to reword parse errors to make it clear that the location given is more like "where I realized there was a problem" instead of "where your mistake is".  I feel like a lot of confusion comes from students expecting the computer to point directly to their mistake, when in fact the computer doesn't understand their code and so doesn't know exactly where the mistake was made.

**Comment by cdsmith** [comment] 2019-09-10 13:15
I'll close and add this comment to the other issue.

**Closed by cdsmith** 2019-09-10 13:15 UTC
Labels: error-message
