### ISSUE TITLE
User-reported unhelpful error message

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1549] opened 2021-12-05 17:54 UTC
**Program:** https://code.world/haskell#Pcpn6B5IYYVeHGoPPgy3TJA

**Comment:**

why?

**Message:**

    CodeWorld programs cannot read from the console.

**Comment by cdsmith** [comment] 2021-12-06 20:52
Duplicate of existing issue.

**Closed by cdsmith** 2021-12-06 20:52 UTC
Labels: error-message
