### ISSUE TITLE
cabal: Could not resolve dependencies:  [__0] trying: codeworld-server-0.1 (user goal)

### ISSUE THREAD

**Issue by liuhui2010518** [google/codeworld#1224] opened 2019-11-03 05:24 UTC
Warning: CodeWorld.App2: could not find link destinations for:
    Double Int IO
Warning: CodeWorld.App: could not find link destinations for:
    Double Int IO StdGen
Documentation created: dist/doc/html/codeworld-api/codeworld-api.txt
===== RUNNING: cabal_install ./codeworld-server ./codeworld-error-sanitizer ./codeworld-compiler ./codeworld-requirements ./codeworld-game-api ./codeworld-prediction ./codeworld-api ./codeworld-game-server ./codeworld-account ./codeworld-auth
Warning: the --global flag is deprecated -- it is generally considered a bad
idea to install packages into the global store
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: codeworld-server-0.1 (user goal)
[__1] unknown package: ormolu (dependency of codeworld-server)
[__1] fail (backjumping, conflict set: codeworld-server, ormolu)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: codeworld-server, ormolu

**Comment by cdsmith** [comment] 2019-11-03 05:49
Perhaps you need to run `cabal update`?  ormolu is definitely in hackage, and has been since Oct 11.

**Comment by liuhui2010518** [comment] 2019-11-03 10:43
> Perhaps you need to run `cabal update`? ormolu is definitely in hackage, and has been since Oct 11.

Thank you for your quick reply. It seems that I choose a not stable branch, reflexdebug branch works well.

**Comment by cdsmith** [comment] 2019-11-04 13:49
The reflexdebug branch is pretty old.  The problem here isn't that CodeWorld isn't working; it's that you're using an old package database that doesn't know about ormolu.  You should be able to run (. base.sh && cabal update) from the codeworld directory to fix that, and still use master.

**Comment by liuhui2010518** [comment] 2019-11-06 01:42
Got it， master works well after compiling to follow you instruction . I use a CDN codemirror.js, cause codemirror-compressed.js  compilation failed In my browser。After that， everthing looks well.  Thank you for your help.

**Comment by cdsmith** [comment] 2019-11-06 01:51
Okay.  Feel free to file another bug for the codemirror failure.  I'll close this one.

**Comment by cdsmith** [comment] 2019-11-08 20:36
I'm reopening this because I'm getting a similar failure running `docker build` from HEAD on a fresh machine.

```
===== RUNNING: cabal_install ./codeworld-server ./codeworld-error-sanitizer ./codeworld-compiler ./codeworld-requirements ./codeworld-game-api ./codeworld-prediction ./codeworld-api ./codeworld-game-server ./codeworld-account ./codeworld-auth
Warning: the --global flag is deprecated -- it is generally considered a bad
idea to install packages into the global store
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: codeworld-server-0.1 (user goal)
[__1] unknown package: ormolu (dependency of codeworld-server)
[__1] fail (backjumping, conflict set: codeworld-server, ormolu)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: codeworld-server, ormolu
```

This is strange, because ormolu is definitely on hackage.

**Comment by cdsmith** [comment] 2019-11-08 20:38
Okay, the problem is this in `install.sh`:

    cabal update --index-state='2019-09-28T01:46:00Z'

That was presumably added to work around a dependency problem, but it excludes ormolu.

**Closed** 2019-11-08 20:41 UTC
