### ISSUE TITLE
User-reported unhelpful error message

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1147] opened 2019-09-06 18:23 UTC
**Program:** https://code.world/#PBuSfdi4rt036II6-XMzRmQ

**Comment:**

give us an example

**Message:**

    program.hs:6:1: error:
        parse error (possibly incorrect indentation or mismatched brackets)

**Comment by cdsmith** [comment] 2019-09-06 22:38
Still cannot do any better, because there is no component that understands what mistake was made.  The only thing I can think of is to call this a duplicate of #597

**Closed by cdsmith** 2019-09-06 22:38 UTC
Labels: error-message
