### ISSUE TITLE
The download of GHC

### ISSUE THREAD

**Issue by Anilople** [google/codeworld#472] opened 2017-04-30 17:52 UTC
I have installed it, but `./install.sh` still choose to download ghc. The problem is, I have to pay a long time to   download it(about  30KB/s).

**Comment by wisn** [comment] 2017-05-04 08:27
You should explain more clear about this. Have you take a look on https://github.com/google/codeworld/issues/435?

**Comment by cdsmith** [comment] 2017-05-04 18:47
CodeWorld installs its own versions of dependencies, including GHC, by design.  You can modify install.sh to avoid doing so, but then I couldn't guarantee that the rest of the install process will succeed with the specific versions you have installed.

If you have a better idea how this should work, can you be specific about what you want?  Otherwise, I think we should close this, as things are working as intended.

**Closed** 2017-05-05 15:24 UTC
