### ISSUE TITLE
User-reported unhelpful error message

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1214] opened 2019-10-31 17:57 UTC
**Program:** https://code.world/#PKfbAVhUWnWApDgs-Vl0EoQ

**Message:**

    program.hs:1:9-22: error: 
        Variable not in scope: drawingOfmouth

**Comment by cdsmith** [comment] 2019-10-31 18:14
The student here wanted `drawingOf(mouth)` and wrote `drawingOfmouth` instead.  In principle, it might be great to recognize that splitting the word was what was intended, but the missing parentheses as well makes this a poor test case.  I'll close this, but would reconsider the principle if we had a more compelling test case.

**Closed by cdsmith** 2019-10-31 18:14 UTC
Labels: error-message
