### ISSUE TITLE
Images with dimension of 1 do not have the same coordinate system!

### ISSUE THREAD

**Issue by 3noch** [google/codeworld#1470] opened 2020-11-19 04:23 UTC
**Shared Program**: https://code.world/haskell#Pd2EwLwlAa7C5HiVCX2SUWA

**Description**

Notice how the "Dude" image is not centered. Choosing a size of 2, 2 for that image and scaling by 0.5 0.5 re-aligns the image to be centered, as seen here: https://code.world/haskell#P_7SnALuYYiUW7GUZ2YWuAw

This is very odd!

**Comment by cdsmith** [comment] 2020-11-19 22:28
Huh.  I don't recall what I was thinking here.  The problem is the rounding at https://github.com/google/codeworld/blob/master/codeworld-api/src/CodeWorld/CanvasM.hs#L172

**Comment by cdsmith** [comment] 2020-11-19 22:29
https://code.world/haskell#P2T2iAEt2zNS7lH_PFjde_A is interesting...

**Comment by cdsmith** [comment] 2020-11-19 22:38
It looks like this happened because https://hackage.haskell.org/package/ghcjs-base-0.2.0.0/docs/JavaScript-Web-Canvas.html#v:drawImage takes `Int` as parameters.  I probably threw in a `round` to make it compile.  That's really the wrong type; JavaScript's drawImage works fine with non-integer arguments.

I can get closer to the right answer by applying scaling myself in the framework, but ultimately this should be fixed in ghcjs-base

**Closed** 2020-11-19 22:53 UTC

**Comment by 3noch** [comment] 2020-11-19 23:07
Wow fantastic sleuthing! Thanks!
