### ISSUE TITLE
User-reported unhelpful error message

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1138] opened 2019-09-03 15:00 UTC
**Program:** https://code.world/#Pj5kISwDZy4nvod5dFJZSBw

**Message:**

    program.hs:3:1-7: warning:
        Defined but not used: petName

**Comment by cdsmith** [comment] 2019-09-03 17:23
This student forgot quotes around a text literally.  They didn't see the helpful message that was added for this case because they also made a second error: they forgot the lettering function.

My first reaction is that I don't know how to do a better job of catching a double error like this.  Without knowing what they were assigned to do or recognizing common names,  I don't see any particular clues that Koda was intended to be text.

**Closed** 2019-09-03 17:23 UTC
Labels: error-message
