### ISSUE TITLE
Bug when running programme

### ISSUE THREAD

**Issue by kammitama5** [google/codeworld#685] opened 2018-07-07 03:11 UTC
When the programme compiles, before it runs successfully , I see this exception error on my local build. 

```
Compiling...uncaught exception in Haskell thread: [Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: http://0.0.0.0:8080/runJS?mode=haskell&dhash=DWP0sayOa4BdcXS2be6v_xA :: h$$ah1 :: line 60542"  data: no]
h$$ah1@http://0.0.0.0:8080/runJS?mode=haskell&dhash=DWP0sayOa4BdcXS2be6v_xA:60542:3
h$runThreadSlice@http://0.0.0.0:8080/runJS?mode=haskell&dhash=DWP0sayOa4BdcXS2be6v_xA:8092:11
h$runThreadSliceCatch@http://0.0.0.0:8080/runJS?mode=haskell&dhash=DWP0sayOa4BdcXS2be6v_xA:8050:12
h$mainLoop@http://0.0.0.0:8080/runJS?mode=haskell&dhash=DWP0sayOa4BdcXS2be6v_xA:8045:9
h$mkForeignCallback/<@http://0.0.0.0:8080/runJS?mode=haskell&dhash=DWP0sayOa4BdcXS2be6v_xA:8588:13

```

**Comment by cdsmith** [comment] 2018-07-12 04:09
@kammitama5 

On your test server, can you do the following?

1. Visit http://0.0.0.0:8080/runJS?mode=haskell&dhash=DWP0sayOa4BdcXS2be6v_xA
2. Look at data/haskell/deploy/DWP/DWP0sayOa4BdcXS2be6v_xA and note the contents
3. Look for data/haskell/user/PXX/PXXXXXXXXXXXXXX (where PXXXXXXXXXXX is the contents of the deply file)?
4. Search for the definition of `h$$a1` and post it here?

That function is doing something that throws an exception.

**Comment by kammitama5** [comment] 2018-07-12 04:16
I built it on my master branch and got this using the weblink:

```
A web handler threw an exception. Details:
data/haskell/deploy/DWP/DWP0sayOa4BdcXS2be6v_xA: openBinaryFile: does not exist (No such file or directory)
```

**Comment by cdsmith** [comment] 2018-07-12 04:32
Huh.  Okay, it looks like you either deleted your data directory at some point, or this error was generated on a different computer from the one you're testing.

Can you reproduce this?  If not, I'm tempted to close the bug, and just chalk it up to random problems in the local environment.

**Comment by cdsmith** [comment] 2018-07-12 04:32
If you can reproduce, can you post the message you see for a new program?

**Comment by kammitama5** [comment] 2018-07-12 04:33
Let me see. I also have  the result of the DPt file 
```
PeYjSNPhYd58_wvFfiUJHsA
```

**Comment by kammitama5** [comment] 2018-07-12 04:34
Yes; you are correct. This is from the other computer that I am not currently on (ie the one where the screen died). So this error, may in fact, not be reproducible.

**Comment by cdsmith** [comment] 2018-07-12 04:40
Is "the DPt file" one where you saw this error?  If so, what was the error message?  (It has a stack trace, which will tell us which JavaScript function to look for in data/haskell/user/PeY/PeYjSNPhYd58_wvFfiUJHsA.js)

**Comment by kammitama5** [comment] 2018-07-12 04:48
The path in the data folder leads to a ```.hs``` file of path ```data/haskell/user/PeY/PeYjSNPhYd58_wvFfiUJHsA.js``` which only has this code in it at the moment 
```
import CodeWorld 
main = debugSimulationOf initial step picture 
initial = 0
step dt x = x + dt
picture x = circle x
```
The problem with this bug is that the computer that generated this bug is not the computer I'm currently working on. The computer that generated this bug is not currently functional (the screen died a few days ago and the OS was wiped). I  wiped the OS shortly before the screen died, but it was on Ubuntu 18.04.

**Comment by kammitama5** [comment] 2018-07-12 04:57
I also just tried to rebuild the same function that I used 
```
program      = animationOf(propellor)
propellor(t) = rotated(solidRectangle(10, 1), 60 * t)
```
and I can't reproduce it on this machine (this one has a better core than the other laptop with the flickering screen that produced the initial error). I don't see any warning errors on this (current) machine. It builds as expected with no warnings and just loads the animation.

**Comment by cdsmith** [comment] 2018-07-12 15:30
Okay, I will close this bug.

The issue about debug controls is actually that the run window is too large.  Currently, it's always set at 500x500, regardless of the screen size.  I guess I hoped everyone could spare at least 500 pixels, but ideally, it would be resizable.  You can file a different bug for that, if you like.

**Closed by cdsmith** 2018-07-12 15:30 UTC
Labels: bug
