### ISSUE TITLE
User-reported unhelpful error message

### ISSUE THREAD

**Issue by codeworld-feedback** [google/codeworld#1127] opened 2019-08-28 20:45 UTC
**Program:** https://code.world/#Pys7bkvz4kb2qluPS1M6CFw

**Comment:**

It's not helpful if you do not show me what I coded and just show me what could possibly be removed in the future.

**Message:**

    program.hs:5:32-41: warning:
        In the use of chartreuse
        (defined in the standard library):
        "Please use RGB(...) instead of chartreuse.
         The variable chartreuse may be removed July 2020."

**Comment by cdsmith** [comment] 2019-08-28 21:13
Duplicate of #1105

**Closed by cdsmith** 2019-08-28 21:13 UTC
Labels: error-message
